### ISSUE TITLE
Cannot get RMSE to plot

### ISSUE THREAD

**Issue by mikevogt** [mikevogt/VARIMAmodel#2]
model_arima = ARIMA(train,order=(2,1,1))
			model_arima_fit = model_arima.fit()

			forcasted=[]
			forcasted= model_arima_fit.forecast(steps=27)[0]           #What is this zero here meant to signify
			
			rmse = self.rootMeanSquareError(forcasted,xArray)
			print("RMSE calculated:")
			print(rmse)

**Comment by madioSane** [comment]
You go mixed up with the variable names. xArray is supposed to be xValArray. We should maybe rename most of our variables conveniently and neatly in the future to avoid this
