### ISSUE TITLE
Features in the Feature List

### ISSUE THREAD

**Issue by RushilPatel0703** [mikevogt/VARIMAmodel#4]
In the forecast window in the feature list, the features 'DateStamps', 'Shares' and 'Ticker', obviously lead to the program crashing since they are not valid features for the model and therefore need to be removed from the list

------code from ArimaModelGui--------
------line 107------

`for column in self.data.columns:` 
       `self.featuresListWidget.addItem(column)`

**Comment by Plakas9** [comment]
You can simply choose which features you want to add by not indexing the features we don't need:

for column in self.data.columns[3:]
self.featuresListWidget.addItem(column):
